name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start docker compose
        run: docker compose up -d

      - name: Install dependencies
        run: docker compose exec app npm ci

      - name: Generate types
        run: docker compose exec app npm run generate-types

      - name: Type check
        run: docker compose exec app npm run type-check

      - name: Lint
        run: docker compose exec app npm run lint

      - name: Check formatting
        run: docker compose exec app npm run format:check

      - name: Test
        run: docker compose exec app npm run test:coverage

      - name: Copy coverage from container
        run: |
          # Create coverage directory with correct permissions
          mkdir -p coverage
          # Copy coverage from container to host
          docker compose cp app:/workspaces/mcp-vikunja/coverage/. ./coverage/
        if: always()

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
        if: always()

      - name: Build
        run: docker compose exec app npm run build

      - name: Stop containers
        if: always()
        run: docker compose down
