name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: './docker-compose.yml'
          up-flags: '-d'

      - name: Install dependencies
        run: docker compose exec app npm ci

      - name: Generate types
        run: docker compose exec app npm run generate-types

      - name: Type check
        run: docker compose exec app npm run type-check

      - name: Lint
        run: docker compose exec app npm run lint

      - name: Check formatting
        run: docker compose exec app npm run format:check

      - name: Test
        run: docker compose exec app npm run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
        if: always()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: docker compose exec app npm run build

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Dependency vulnerability scanning
      - name: Security audit dependencies
        run: npm audit
        continue-on-error: true # npm audit can fail on non-critical issues

      # Static code analysis with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # License compliance checking
      - name: Check licenses
        run: npx license-checker --production \
          --onlyAllow "MIT;ISC;BSD-2-Clause;BSD-3-Clause;Apache-2.0" \
          --excludePrivatePackages \
          --summary
